import {Recipe} from "../recipe";
import "../ingredients";
import {can, gram, milliliter, piece, spice, tableSpoon, teeSpoon} from "../units";
import {
    basilikum,
    brokkoli,
    bruehe,
    champignon,
    cocktailtomaten,
    cremeFraiche,
    curry,
    erbsen,
    feta,
    frischkaese,
    fruehlingszwiebel,
    gefluegel,
    petersilie,
    gehackteTomaten,
    getrockneteTomate,
    hackfleisch,
    italienischeKrauter,
    knoblauchzehe,
    kohlrabi,
    kokosmilch,
    kreuzkuemmel,
    kuerbis,
    kurzeNudeln,
    milch,
    moehre,
    muskat,
    oel,
    oregano,
    paprika,
    paprikapulver,
    parmesan,
    pinienkerne,
    reibekaese,
    reis,
    roteLinsen,
    sahne,
    salami,
    salbeiblaetter,
    speckwuerfel,
    spinat,
    staudensellerie,
    thunfisch,
    tomatenmark,
    zucchini,
    zwiebel,
    quinoa,
    cranberrys,
    walnuesse,
    butter,
    zitrone,
    kidneyBohnen,
    mais,
    avocado,
    aubergine,
    krauterDerProvence,
    lachsilet,
    bulgur,
    grosseTomate,
    gurke,
    zitronensaft,
    ajvar,
    minze,
    joghurt,
    couscous,
    harissa,
    cashewnuesse,
    ingwer,
    mango, wasser, zucker, zitronengrasPaste, kartoffeln, lauch, berglinsen, balsamicoEssig, senf, wiener
} from "../ingredients";

const onepot: string = "One-Pot";
export const onepotRecipes: Recipe[] = [
    {
        name: "Nudeln mit Brokkoli und Tomaten",
        book: onepot,
        page: 36,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(brokkoli,1),
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            gram(getrockneteTomate,100),
            tableSpoon(oel, 1),
            gram(kurzeNudeln, 250),
            milliliter(bruehe, 400),
            milliliter(milch, 300),
            tableSpoon(petersilie, 2),
            gram(feta, 50),
        ]
    },
    {
        name: "Nudeln Primavera",
        book: onepot,
        page: 40,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(brokkoli,1),
            piece(zwiebel,1),
            gram(champignon,100),
            gram(kurzeNudeln, 250),
            milliliter(bruehe, 500),
            milliliter(sahne, 250),
            gram(spinat, 150),
        ]
    },
    {
        name: "Nudeln Cabonara",
        book: onepot,
        page: 40,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(zucchini,1),
            piece(knoblauchzehe,1),
            gram(speckwuerfel, 150),
            tableSpoon(oel, 1),
            gram(kurzeNudeln, 250),
            milliliter(bruehe, 400),
            gram(erbsen, 100),
            milliliter(sahne, 300),
            tableSpoon(petersilie, 2),
            gram(parmesan, 50)
        ]
    },
    {
        name: "Nudeln mit Hackfleisch und Paprika",
        book: onepot,
        page: 41,
        exclusivelyWeekend: false,
        cookingTime: 15,
        prepTime: 10,
        ingredients: [
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            piece(paprika,2),
            tableSpoon(oel, 1),
            gram(hackfleisch, 400),
            gram(kurzeNudeln, 250),
            milliliter(bruehe, 700),
            tableSpoon(tomatenmark, 3),
            tableSpoon(basilikum, 2),
            spice(paprikapulver),
            spice(kreuzkuemmel),
        ]
    },
    {
        name: "Bunte Thai-Curry Nudeln",
        book: onepot,
        page: 44,
        exclusivelyWeekend: false,
        cookingTime: 15,
        prepTime: 10,
        ingredients: [
            piece(paprika,2),
            piece(moehre,1),
            piece(fruehlingszwiebel,3),
            gram(gefluegel,400),
            gram(erbsen,200),
            gram(kurzeNudeln,250),
            tableSpoon(curry, 2),
            can(kokosmilch, 1),
            milliliter(bruehe, 300)
        ]
    },
    {
        name: "Nudeln mit Linsenbolognese",
        book: onepot,
        page: 46,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            gram(roteLinsen,200),
            piece(staudensellerie,2),
            piece(moehre,2),
            tableSpoon(oel, 1),
            gram(kurzeNudeln, 250),
            milliliter(bruehe, 800),
            can(gehackteTomaten, 1),
            tableSpoon(italienischeKrauter, 2)
        ]
    },
    {
        name: "Nudeln mit Spinat, Tomaten und Feta",
        book: onepot,
        page: 47,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            gram(cocktailtomaten,200),
            gram(pinienkerne,10),
            tableSpoon(oel, 1),
            gram(kurzeNudeln, 250),
            milliliter(milch, 400),
            milliliter(bruehe, 400),
            gram(spinat, 250),
            tableSpoon(frischkaese, 2),
            gram(feta, 50),
            spice(muskat),
        ]
    },
    {
        name: "Nudeln mit Hähnchen und Paprika",
        book: onepot,
        page: 48,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(paprika,1),
            gram(champignon,100),
            piece(zwiebel,1),
            gram(gefluegel,400),
            gram(kurzeNudeln, 250),
            can(gehackteTomaten, 1),
            milliliter(bruehe, 600),
            tableSpoon(basilikum, 2),
            teeSpoon(oregano, 0.5),
        ]
    },
    {
        name: "Pizza-Nudeltopf",
        book: onepot,
        page: 48,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            gram(salami,200),
            tableSpoon(oel, 1),
            gram(kurzeNudeln, 250),
            can(gehackteTomaten, 1),
            milliliter(bruehe, 600),
            tableSpoon(basilikum, 2),
            gram(reibekaese,100),
        ]
    },
    {
        name: "Kürbis-Nudeln",
        book: onepot,
        page: 54,
        exclusivelyWeekend: false,
        cookingTime: 15,
        prepTime: 15,
        ingredients: [
            piece(zwiebel,1),
            gram(kuerbis,500),
            piece(salbeiblaetter,8),
            tableSpoon(oel,2),
            gram(kurzeNudeln,250),
            milliliter(milch,200),
            milliliter(sahne,200),
            milliliter(bruehe,400),
            gram(parmesan,50),
        ]
    },
    {
        name: "Nudeln mit Thunfisch",
        book: onepot,
        page: 55,
        exclusivelyWeekend: false,
        cookingTime: 5,
        prepTime: 10,
        ingredients: [
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            gram(kurzeNudeln,250),
            can(thunfisch,1),
            can(gehackteTomaten, 1),
            milliliter(bruehe,500),
            tableSpoon(basilikum,2),
            tableSpoon(cremeFraiche,3),
            gram(parmesan,50),
        ]
    },
    {
        name: "Bunter Gemüsereis",
        book: onepot,
        page: 57,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(zwiebel,1),
            piece(moehre,1),
            gram(kohlrabi,100),
            gram(champignon,100),
            tableSpoon(oel,1),
            gram(reis,180),
            milliliter(bruehe,400),
            milliliter(sahne,200),
            tableSpoon(petersilie,2),
            gram(erbsen,250),
            gram(parmesan,50),
        ]
    },
    {
        name: "Hähnchen-Brokkoli-Quinoa",
        book: onepot,
        page: 58,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 15,
        ingredients: [
            gram(quinoa,160),
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            piece(brokkoli,1),
            piece(paprika,1),
            gram(gefluegel,400),
            tableSpoon(oel,1),
            milliliter(bruehe,800),
            tableSpoon(petersilie,2),
            gram(cranberrys,50),
            gram(walnuesse,50),
        ]
    },
    {
        name: "Zitronen-Risotto mit Erbsen",
        book: onepot,
        page: 60,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 15,
        ingredients: [
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            piece(zitrone,1),
            tableSpoon(oel,2),
            gram(reis,160),
            milliliter(bruehe,600),
            gram(erbsen,100),
            tableSpoon(butter,2),
            tableSpoon(petersilie,2),
            gram(parmesan,20),
        ]
    },
    {
        name: "Mexikanischer Reis",
        book: onepot,
        page: 62,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            can(kidneyBohnen,1),
            can(mais,1),
            piece(paprika,1),
            piece(avocado,1),
            tableSpoon(oel,2),
            gram(reis,160),
            milliliter(bruehe,300),
            can(gehackteTomaten, 1),
            tableSpoon(petersilie,1),
            spice(kreuzkuemmel),
            spice(paprikapulver),
        ]
    },
    {
        name: "Reis mit Ratatouille Gemüse",
        book: onepot,
        page: 64,
        exclusivelyWeekend: false,
        cookingTime: 15,
        prepTime: 10,
        ingredients: [
            piece(zwiebel,1),
            piece(knoblauchzehe,1),
            piece(zucchini,1),
            piece(aubergine,1),
            piece(paprika,1),
            tableSpoon(oel,2),
            gram(reis,160),
            milliliter(bruehe,400),
            can(gehackteTomaten, 1),
            tableSpoon(krauterDerProvence,2),
            gram(reis,50),
        ]
    },
    {
        name: "Curry-Reis mit Lachs",
        book: onepot,
        page: 64,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            piece(lachsilet,2),
            piece(zucchini,1),
            piece(fruehlingszwiebel,4),
            gram(reis,160),
            gram(erbsen,100),
            milliliter(bruehe,200),
            can(kokosmilch,1),
            tableSpoon(curry,2),
            tableSpoon(petersilie,2),
        ]
    },
    {
        name: "Tomatiger Bulgursalat",
        book: onepot,
        page: 65,
        exclusivelyWeekend: false,
        cookingTime: 10,
        prepTime: 10,
        ingredients: [
            milliliter(bruehe,450),
            gram(bulgur,160),
            piece(paprika,1),
            piece(grosseTomate,2),
            piece(gurke,2),
            piece(zwiebel,1),
            tableSpoon(petersilie,2),
            tableSpoon(oel,2),
            tableSpoon(zitronensaft,1),
            tableSpoon(tomatenmark,4),
            tableSpoon(ajvar,2),
            gram(feta,50),
        ]
    },
    {
        name: "Orientalischer Couscous",
        book: onepot,
        page: 65,
        exclusivelyWeekend: false,
        cookingTime: 15,
        prepTime: 10,
        ingredients: [
            piece(brokkoli,1),
            piece(moehre,2),
            piece(minze,4),
            tableSpoon(zitronensaft,2),
            tableSpoon(oel,2),
            gram(joghurt,200),
            milliliter(bruehe,700),
            gram(couscous,160),
            tableSpoon(harissa,1),
            tableSpoon(curry,1),
        ]
    },
    {
        name: "Mango-Reis-Curry",
        book: onepot,
        page: 66,
        exclusivelyWeekend: false,
        cookingTime: 15,
        prepTime: 10,
        ingredients: [
            piece(ingwer,1),
            piece(knoblauchzehe,1),
            gram(gefluegel,500),
            piece(mango,1),
            piece(fruehlingszwiebel,4),
            tableSpoon(oel,1),
            tableSpoon(curry,2),
            can(kokosmilch, 1),
            milliliter(wasser, 200),
            gram(reis, 160),
            tableSpoon(zucker,1),
            gram(erbsen,200),
            tableSpoon(zitronengrasPaste, 0.5),
            gram(cashewnuesse,50),
        ]
    },
    {
        name: "Linseneintopf",
        book: onepot,
        page: 70,
        exclusivelyWeekend: true,
        cookingTime: 15,
        prepTime: 40,
        ingredients: [
            piece(zwiebel,1),
            gram(speckwuerfel,100),
            tableSpoon(butter,1),
            gram(berglinsen,250),
            milliliter(bruehe, 1500),
            piece(moehre,2),
            piece(lauch,1),
            gram(kartoffeln,200),
            piece(wiener,2),
            spice(zucker),
            tableSpoon(senf,1),
            tableSpoon(petersilie,1),
            tableSpoon(balsamicoEssig,1),
        ]
    },
];


